name: Composer Diff

on:
    pull_request:
        types:
            - opened
            - synchronize
        paths:
            - 'composer.lock'

jobs:
    check-diff:
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@v5

            -   name: Run Composer Diff Action
                uses: eonx-com/composer-diff-action@v1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
